# Updated workflow file

name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build the project
        run: pnpm draft-assistant:build --prod -- --output-path=dist --base-href=/FF-DA/
      - name: Deploy
        run: echo 'Deploying...'
